apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80 # 클러스터 내부 통신에 사용하는 port
      targetPort: 80 # 파드 내부의 애플리케이션 포트
      nodePort: 30084 # 외부 포트
  type: NodePort