apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql  # Deployment의 labels와 일치해야 합니다.
  ports:
    - protocol: TCP
      port: 3306           # 클러스터 내부에서 사용하는 포트
      targetPort: 3306     # MySQL 컨테이너의 포트
  type: ClusterIP