services:
  mysql:
    image: mysql:8.0.38
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rlqja
      MYSQL_DATABASE: todolist
    ports:
      - 3307:3306
    volumes:
      - todolistdata:/var/lib/mysql
      - ./mysql/grant_privileges.sql:/docker-entrypoint-initdb.d/grant_privileges.sql
    networks:
      - testnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  spring:
    build:
      context: ./spring
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    networks:
      - testnet
    depends_on:
      # - mysql
      mysql:
        condition: service_healthy
    environment:
      - spring_datasource_url=jdbc:mysql://mysql:3306/todolist?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      - spring_datasource_username=root
      - spring_datasource_password=rlqja
  
  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - 80:8000
    networks:
      - testnet
    depends_on:
      - spring
    volumes:
      - ./react/default.conf:/etc/nginx/conf.d/default.conf
      - ./react/dist:/usr/share/nginx/html

networks:
  testnet:

volumes:
  todolistdata: